# Generated by Django 5.0.1 on 2024-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is this a premium article?'),
        ),
    ]
